name: Build and Publish

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest jellyfin-web release
        id: jellyfin_web_release
        run: |
          LATEST_RELEASE=$(curl -sL https://api.github.com/repos/jellyfin/jellyfin-web/releases/latest)
          LATEST_VERSION=$(echo "$LATEST_RELEASE" | jq -r '.tag_name' | sed 's/v//')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Clone jellyfin-web
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-web'
          platform: 'github'
          path: 'jellyfin-web'
          ref: 'v${{ steps.jellyfin_web_release.outputs.version }}'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '>=14'

      - name: Build jellyfin-web
        run: |
          cd jellyfin-web
          npm install
          npm run build

      - name: Clone jellyfin-tizen
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-tizen'
          platform: 'github'
          path: 'jellyfin-tizen'

      - name: Modify jellyfin-tizen/package.json
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          path: 'jellyfin-tizen/package.json'
          data: |
            {
              "name": "@elfpie/jellyfin-tizen",
              "packageType": "app",
              "appName": "Jellyfin",
              "appPath": "index.html",
              "version": "${{ steps.jellyfin_web_release.outputs.version }}",
              "keys": [
                "MediaPlayPause", "MediaPlay", "MediaPause", "MediaStop",
                "MediaTrackPrevious", "MediaTrackNext", "MediaRewind", "MediaFastForward"
              ]
            }

      - name: Set tizen-adapter.js app version
        uses: htsnvhoang/find-replace-multiple@master
        with:
          finds: |
            version: 'DEVELOPMENT'
          replaces: |
            version: '${{ steps.info.outputs.version }}'
          include: "tizen-adapter.js"
          separator: "___"
            
      - name: Enable TrueHD Audio
        uses: htsnvhoang/find-replace-multiple@master
        with:
          finds: |
            return profileBuilder({ enableMkvProgressive: false, enableSsaRender: true });
          replaces: |
            return profileBuilder({ enableMkvProgressive: false, enableSsaRender: true, supportsTrueHd: true });
          include: "jellyfin-tizen/tizen.js"
          separator: "___"

      - name: Include tizen-adapter.js in the app
        uses: htsnvhoang/find-replace-multiple@master
        with:
          finds: |
            webapis.setAttribute('src', '$WEBAPIS/webapis/webapis.js');
          replaces: |
            webapis.setAttribute('src', '../tizen-adapter.js');
          include: "jellyfin-tizen/gulpfile.babel.js"
          separator: "___"

      - name: Inject skip-intro-button.js in the app
        uses: htsnvhoang/find-replace-multiple@master
        with:
          finds: |
            injectTarget.insertBefore(tizen, apploader);
          replaces: |
            injectTarget.insertBefore(tizen, apploader);

            // inject skip-intro-button.js
            const skipIntro = this.createElement('script');
            skipIntro.setAttribute('src', 'https://cdn.jsdelivr.net/gh/jumoog/intro-skipper/ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js');
            skipIntro.setAttribute('defer', '');
            injectTarget.insertBefore(skipIntro, apploader);
          include: "jellyfin-tizen/gulpfile.babel.js"
          separator: "___"

      - name: Build jellyfin-tizen
        run: |
          cp tizen-adapter.js jellyfin-tizen/
          cd jellyfin-tizen
          rm .gitignore
          JELLYFIN_WEB_DIR=../jellyfin-web/dist npm ci --no-audit

      - name: Publish new @elfpie/jellyfin-tizen package version
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: jellyfin-tizen
          access: public

      - name: Release Build Result
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.info.outputs.version }}
          body: "A new version of @elfpie/jellyfin-tizen has been published based on jellyfin-web v${{ steps.jellyfin_web_release.outputs.version }}."
